// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://postgres.ciidxcqqxmxfkvjahbks:Dynamic%40%40%40%21%40%23123@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true",
    directUrl: "postgresql://postgres.ciidxcqqxmxfkvjahbks:Dynamic%40%40%40%21%40%23123@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres",
  },
});
